// <auto-generated />
using System;
using DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataModel.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataModel.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanDuration")
                        .HasColumnType("int");

                    b.Property<int>("LoanType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookID");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "Suzanne Collins",
                            ISBN = "9780439023481.00",
                            LoanDuration = 28,
                            LoanType = 1,
                            Title = "The Hunger Gamer"
                        },
                        new
                        {
                            BookID = 2,
                            Author = "George Orwell",
                            ISBN = "1110141036141.00",
                            LoanDuration = 28,
                            LoanType = 1,
                            Title = "1984"
                        },
                        new
                        {
                            BookID = 3,
                            Author = "Aldous Huxely",
                            ISBN = "2220060929871.00",
                            LoanDuration = 1,
                            LoanType = 0,
                            Title = "Brave New World"
                        },
                        new
                        {
                            BookID = 4,
                            Author = "Athur Conan Doyle",
                            ISBN = "1234564389.00",
                            LoanDuration = 28,
                            LoanType = 1,
                            Title = "The Hound of the Baskervilles"
                        },
                        new
                        {
                            BookID = 5,
                            Author = "Leonardo da Vinci",
                            ISBN = "123456789196.00",
                            LoanDuration = 1,
                            LoanType = 0,
                            Title = "Literary works of Leonardo da Vinci"
                        },
                        new
                        {
                            BookID = 6,
                            Author = "Eoin Colfer",
                            ISBN = "9780786851478.00",
                            LoanDuration = 28,
                            LoanType = 1,
                            Title = "The Arctic Incident"
                        },
                        new
                        {
                            BookID = 7,
                            Author = "P.W Atkins",
                            ISBN = "716720736.00",
                            LoanDuration = 1,
                            LoanType = 0,
                            Title = "Physical Chemistry"
                        },
                        new
                        {
                            BookID = 8,
                            Author = "Roger Freedman",
                            ISBN = "716746476.00",
                            LoanDuration = 28,
                            LoanType = 1,
                            Title = "Universe"
                        });
                });

            modelBuilder.Entity("DataModel.Loan", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoanIssueDate")
                        .HasColumnType("date");

                    b.HasKey("BookID", "MemberID");

                    b.HasIndex("MemberID");

                    b.ToTable("Loan");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            MemberID = 1,
                            LoanIssueDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookID = 2,
                            MemberID = 1,
                            LoanIssueDate = new DateTime(2026, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookID = 3,
                            MemberID = 5,
                            LoanIssueDate = new DateTime(2026, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookID = 4,
                            MemberID = 6,
                            LoanIssueDate = new DateTime(2026, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookID = 7,
                            MemberID = 8,
                            LoanIssueDate = new DateTime(2026, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DataModel.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberID");

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            FirstName = "Elizabeth",
                            SecondName = "Anderson"
                        },
                        new
                        {
                            MemberID = 2,
                            FirstName = "Catherine",
                            SecondName = "Autier Miconi"
                        },
                        new
                        {
                            MemberID = 3,
                            FirstName = "Thomas",
                            SecondName = "Axen"
                        },
                        new
                        {
                            MemberID = 4,
                            FirstName = "Jean Phillipe",
                            SecondName = "Bagel"
                        },
                        new
                        {
                            MemberID = 5,
                            FirstName = "Anna",
                            SecondName = "Bedecs"
                        },
                        new
                        {
                            MemberID = 6,
                            FirstName = "John",
                            SecondName = "Edwards"
                        },
                        new
                        {
                            MemberID = 7,
                            FirstName = "Alexanger",
                            SecondName = "Eggerer"
                        },
                        new
                        {
                            MemberID = 8,
                            FirstName = "Michael",
                            SecondName = "Entin"
                        },
                        new
                        {
                            MemberID = 9,
                            FirstName = "Daniel",
                            SecondName = "Goldschmidt"
                        },
                        new
                        {
                            MemberID = 10,
                            FirstName = "Antonio",
                            SecondName = "Gratacos Silsona"
                        },
                        new
                        {
                            MemberID = 11,
                            FirstName = "Carlos",
                            SecondName = "Grilo"
                        },
                        new
                        {
                            MemberID = 12,
                            FirstName = "Jonas",
                            SecondName = "Hasselberg"
                        });
                });

            modelBuilder.Entity("DataModel.Loan", b =>
                {
                    b.HasOne("DataModel.Book", "Book")
                        .WithMany("IsOnLoan")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Member", "Member")
                        .WithMany("HasLoans")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DataModel.Book", b =>
                {
                    b.Navigation("IsOnLoan");
                });

            modelBuilder.Entity("DataModel.Member", b =>
                {
                    b.Navigation("HasLoans");
                });
#pragma warning restore 612, 618
        }
    }
}
